import requests

requisicao = requests.get('https://pokeapi.co/api/v2/pokemon/ditto')
conteudo = requisicao.json()

print(conteudo)
print(len(conteudo))

print(conteudo['abilities'])

print(conteudo['abilities'][0]['ability'])
requisicao2 = requests.get(f"{conteudo['abilities'][0]['ability']['url']}")
conteudo2 = requisicao2.json()
print(conteudo2)
print(len(conteudo2))
print(conteudo2['effect_changes'])
print(conteudo2['effect_entries'])
print(conteudo2['flavor_text_entries'])
print(conteudo2['generation'])
print(conteudo2['id'])
print(conteudo2['is_main_series'])
print(conteudo2['name'])
print(conteudo2['names'])
print(conteudo2['pokemon'])

print(conteudo['abilities'][1]['ability'])
requisicao3 = requests.get(f"{conteudo['abilities'][1]['ability']['url']}")
conteudo3 = requisicao3.json()
print(conteudo3)
print(len(conteudo3))
print(conteudo3['effect_changes'])
print(conteudo3['effect_entries'])
print(conteudo3['flavor_text_entries'])
print(conteudo3['generation'])
print(conteudo3['id'])
print(conteudo3['is_main_series'])
print(conteudo3['name'])
print(conteudo3['names'])
print(conteudo3['pokemon'])

# print(conteudo['base_experience'])
# print(conteudo['forms'])
# print(conteudo['game_indices'])
# print(conteudo['height'])
# print(conteudo['held_items'])
# print(conteudo['id'])
# print(conteudo['is_default'])
# print(conteudo['location_area_encounters'])
# print(conteudo['moves'])
# print(conteudo['name'])
# print(conteudo['order'])
# print(conteudo['past_types'])
# print(conteudo['species'])
# print(conteudo['sprites'])
# print(conteudo['stats'])
# print(conteudo['types'])
# print(conteudo['weight'])
